# Generated by Django 5.2.3 on 2025-07-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.CharField()),
                ('image', models.ImageField(upload_to='', verbose_name='show/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
