# Generated by Django 5.2.3 on 2025-08-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='decision',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='decision_images',
            field=models.ImageField(blank=True, upload_to='decision/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='task',
            name='memo_images',
            field=models.ImageField(blank=True, upload_to='memo/%Y/%m/%d/'),
        ),
    ]
