# Generated by Django 5.2.3 on 2025-08-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_decision_task_decision_images_task_memo_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='data_complete',
            field=models.DateField(blank=True, null=True),
        ),
    ]
