# Generated by Django 5.2.3 on 2025-08-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_created_alter_task_data_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='line',
            field=models.CharField(choices=[('1', 'PK1'), ('2', 'PK2'), ('3', 'PK3')], default='PK1', max_length=100),
        ),
    ]
