# Generated by Django 5.2.3 on 2025-08-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_rating', '-vote_total', '-title']},
        ),
    ]
