# Generated by Django 5.2.3 on 2025-07-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('descriptions', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
